services:
  - type: web
    name: lumea-cms
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: corepack pnpm install --frozen-lockfile --filter cms... && corepack pnpm --filter cms build
    startCommand: cd cms && node node_modules/@strapi/strapi/bin/strapi.js start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
      - key: COREPACK_ENABLE_DOWNLOAD_PROMPT
        value: 0
      - key: NODE_VERSION
        value: 24
      - key: IS_PROXIED
        value: true
      - key: PUBLIC_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: WEB_REVALIDATE_URL
        sync: false
      - key: WEB_REVALIDATE_SECRET
        sync: false
